import {config} from './config.js?v=budget3';
import {travel,matchPackages} from './adapters.js?v=budget3';
const $=s=>document.querySelector(s);
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const el=(tag,text,className)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node;};
let catalog=[],history=[],proposal=null,busy=false;
const form=$('#trip-form'),messages=$('#messages');const welcome=messages.firstElementChild.cloneNode(true);
function getTrip(){const d=new FormData(form);return {destination:d.get('destination'),days:Number(d.get('days')),travelers:Number(d.get('travelers')),budget:Number(d.get('budget')),style:d.get('style'),interests:d.getAll('interests')};}
function setTrip(t){for(const key of ['destination','days','travelers','budget','style'])form.elements[key].value=t[key];form.querySelectorAll('[name=interests]').forEach(i=>i.checked=t.interests.includes(i.value));invalidate();}
function invalidate(){proposal=null;$('#proposal').hidden=true;messages.querySelectorAll('.chat-recommendations').forEach(n=>n.remove());}
form.addEventListener('input',invalidate);
function message(text,role='assistant',record=true){const box=el('div',undefined,'message '+role);if(role==='assistant')box.append(el('span','SABLE & SKY','speaker'));box.append(el('p',text));messages.append(box);messages.scrollTop=messages.scrollHeight;if(record){history.push({role,content:text});history=history.slice(-20);}return box;}
function loading(value){busy=value;$('#chat-form button').disabled=value;form.querySelector('button[type=submit]').disabled=value;$('#reset-chat').disabled=value;document.querySelectorAll('[data-prompt]').forEach(b=>b.disabled=value);messages.setAttribute('aria-busy',String(value));}
function renderPackages(filter='all'){const root=$('#packages');root.replaceChildren();const selected=catalog.filter(p=>filter==='all'||p.country===filter);for(const p of selected){const card=el('article',undefined,'package-card'),photo=el('div',undefined,'package-photo'),img=el('img');img.src=p.image;img.alt=p.alt;img.loading='lazy';photo.append(img,el('span',p.tag,'package-tag'));const bottom=el('div',undefined,'package-bottom'),price=el('span','From ');price.append(el('strong',money(p.price)),document.createTextNode(' / person'));const button=el('button','View journey ↗');button.setAttribute('aria-label',`View ${p.title}`);button.addEventListener('click',()=>openPackage(p));bottom.append(price,button);card.append(photo,el('div',`${p.country.toUpperCase()} / ${p.days===null?'DURATION ON REQUEST':p.days+' DAYS'} / PRIVATE`, 'package-meta'),el('h3',p.title),el('p',p.description),bottom);root.append(card);}if(!selected.length)root.append(el('p','No journeys to show. Try another destination.','empty'));}
function openPackage(p){if(p.source==='mcp'){openConnectedPackage(p);return;}const root=$('#dialog-content');root.replaceChildren(el('p',`${p.country.toUpperCase()} · ${p.days?p.days+' DAYS':'DURATION ON REQUEST'}`,'eyebrow'));const title=el('h2',p.title);title.id='dialog-title';root.append(title,el('p',p.route),el('p',p.description));const list=el('ol');p.stops.forEach(s=>list.append(el('li',s)));root.append(list,el('p',`Illustrative price from ${money(p.price)} per person, based on two sharing. Includes sample stays, private guiding, game drives, park fees, and ground transfers. Excludes international flights, insurance, visas, tips, and optional activities.`),el('p','Sample itinerary only. No accommodation or availability is confirmed.','fine'));const customize=el('button','Make this journey mine ↗','button green');customize.addEventListener('click',()=>{setTrip({...getTrip(),destination:p.country,days:p.days,budget:p.price,interests:p.id==='coast'?['Wildlife','Beach']:['Wildlife']});$('#package-dialog').close();location.hash='concierge';form.elements.destination.focus({preventScroll:true});message(`Let’s use “${p.title}” as your starting point. I’ve filled in the sample duration and per-person budget. Adjust them to make this your own.`);});root.append(customize);$('#package-dialog').showModal();$('#package-dialog').scrollTop=0;$('#dialog-title').setAttribute('tabindex','-1');$('#dialog-title').focus({preventScroll:true});}
$('#package-dialog .dialog-close').addEventListener('click',()=>$('#package-dialog').close());
$('#package-dialog').addEventListener('click',e=>{if(e.target===$('#package-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
function renderProposal(p){const root=$('#proposal');root.className='proposal';root.replaceChildren();const head=el('div',undefined,'proposal-head'),intro=el('div');intro.append(el('p','YOUR FIRST CHAPTER · SAMPLE ITINERARY','eyebrow'),el('h3',p.title),el('p',`${p.trip.days} days · ${p.trip.travelers} travelers · ${p.trip.style}`));const price=el('div');price.append(el('p',`${money(p.estimate)} / person`),el('p',`Total for all ${p.trip.travelers} travelers: ${money(p.total)} · illustrative estimate`,'fine'));head.append(intro,price);root.append(head);const list=el('ol');p.stops.forEach(s=>{const li=el('li');li.append(el('strong',`${s.label} · ${s.place}`),document.createTextNode(s.detail));list.append(li);});root.append(list);p.warnings.forEach(w=>root.append(el('p',w)));root.append(el('p','Includes assumed stays, guiding, game drives, park fees, and ground transfers. Excludes international flights, travel insurance, visas, tips, and optional activities. Dates, availability, exact routing, and final prices are not confirmed.','fine'));const actions=el('div',undefined,'actions'),download=el('button','Download my trip brief ↓','button green'),contact=el('a','Discuss this journey ↗','text-link dark');contact.href='#contact';download.addEventListener('click',downloadBrief);contact.addEventListener('click',()=>{$('#contact-form').elements.message.value=`I’m interested in ${p.title}: ${p.trip.days} days for ${p.trip.travelers} travelers. Budget: ${money(p.trip.budget)} per person. Interests: ${p.trip.interests.join(', ')}.`;});actions.append(download,contact);root.append(actions);root.hidden=false;root.setAttribute('tabindex','-1');root.focus({preventScroll:true});root.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});}
function downloadBrief(){if(!proposal)return;const p=proposal;const content=['SABLE & SKY — YOUR SAFARI BRIEF','DEMONSTRATION ONLY — NOT A QUOTE OR RESERVATION','',p.title,`${p.trip.days} days | ${p.trip.travelers} travelers | ${p.trip.style}`,`Budget per person: ${money(p.trip.budget)}`,`Interests: ${p.trip.interests.join(', ')||'Open to ideas'}`,`Illustrative estimate: ${money(p.estimate)} per person / ${money(p.total)} total`,'',...p.stops.map(s=>`${s.label}: ${s.place}\n${s.detail}`),'',...p.warnings,'','Assumed inclusions: accommodation, guiding, game drives, park fees, ground transfers.','Exclusions: international flights, insurance, visas, gratuities, optional activities.','All routing, dates, prices, and availability require specialist confirmation.'].join('\n');const url=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'})),a=el('a');a.href=url;a.download='sable-and-sky-trip-brief.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
form.addEventListener('submit',async e=>{e.preventDefault();if(busy||!form.reportValidity())return;if(config.mode==='n8n'){send('Find original safari packages matching my current travel preferences. Show the returned packages and all essential conditions without changing their prices or itineraries.');return;}loading(true);const pending=message('Considering your journey…','assistant',false);try{const snapshot=getTrip();const p=await travel.createProposal(snapshot);if(JSON.stringify(snapshot)!==JSON.stringify(getTrip())){message('Your preferences changed while I was preparing that outline. Create your journey again to use the updated details.');return;}proposal=p;message(`Your sample ${p.trip.days}-day journey is ready below. It is a starting point, with an illustrative estimate of ${money(p.estimate)} per person.`);renderMatches(matchPackages(p.trip),p.trip);renderProposal(p);}catch(error){message(error.message||'Something went wrong. Please try again.');}finally{pending.remove();loading(false);}});
async function send(text){if(busy||!text.trim())return;if(!form.reportValidity()){location.hash='concierge';return;}const snapshot=getTrip();message(text,'user');$('#chat-input').value='';loading(true);const pending=message('Your concierge is considering…','assistant',false);try{const result=await travel.sendMessage({message:text,trip:snapshot,history:history.slice(0,-1)});if(JSON.stringify(snapshot)===JSON.stringify(getTrip())){setTrip(result.trip);message(result.reply);renderMatches(result.matches||(config.mode==='mock'?matchPackages(result.trip):[]),result.trip);}else message('Your planning fields changed while I was replying. I have kept your latest settings. Send your message again to continue from them.');}catch(error){message(error.message||'Unable to reply. Please try again.');}finally{pending.remove();loading(false);}}
$('#chat-form').addEventListener('submit',e=>{e.preventDefault();send($('#chat-input').value);});
$('#chat-input').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();send(e.target.value);}});
document.querySelectorAll('[data-prompt]').forEach(b=>b.addEventListener('click',()=>send(b.dataset.prompt)));
$('#reset-chat').addEventListener('click',()=>{travel.resetSession?.();history=[];messages.replaceChildren(welcome.cloneNode(true));form.reset();$('#chat-input').value='';invalidate();});
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});renderPackages(b.dataset.filter);}));
document.querySelectorAll('[data-destination]').forEach(b=>b.addEventListener('click',()=>{form.elements.destination.value=b.dataset.destination;invalidate();location.hash='concierge';form.elements.destination.focus({preventScroll:true});}));
$('.menu-toggle').addEventListener('click',()=>{const open=$('#navigation').classList.toggle('open');$('.menu-toggle').setAttribute('aria-expanded',String(open));});
$('#navigation').addEventListener('click',e=>{if(e.target.closest('a')){$('#navigation').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false');}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#navigation').classList.contains('open')){$('#navigation').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false');$('.menu-toggle').focus();}});
$('#contact-form').addEventListener('submit',async e=>{e.preventDefault();const contact=e.currentTarget,button=contact.querySelector('button');button.disabled=true;$('#contact-status').textContent='Preparing your preview…';try{const response=await travel.submitEnquiry({...Object.fromEntries(new FormData(contact)),trip:proposal?.trip||getTrip()});$('#contact-status').textContent=response.message;}catch(error){$('#contact-status').textContent=error.message||'Unable to prepare your enquiry. Please try again.';}finally{button.disabled=false;}});
$('#year').textContent=new Date().getFullYear();
try{catalog=await travel.listPackages();renderPackages();}catch(error){$('#packages').textContent='The collection is temporarily unavailable. You can still explore the planner below.';}


function renderMatches(matches,trip){
 messages.querySelectorAll('.chat-recommendations').forEach(n=>n.remove());
 const section=el('section',undefined,'chat-recommendations');section.setAttribute('aria-label','Safari packages matched to your preferences');section.append(el('p','OPTIONS WITHIN YOUR BUDGET','speaker'),el('p',`Selected for ${trip.days} days, ${trip.travelers} travelers and ${money(trip.budget)} per person. ${config.mode==='n8n'?'Package details are shown as returned. Changes require a new supplier-confirmed proposal.':'These sample packages can be adapted; final prices may change.'}`,'match-intro'));
 if(!matches.length){section.append(el('p','No matching packages were returned for these preferences. Tell your concierge what you would like to adjust.'));}
 const cards=el('div',undefined,'chat-match-grid');
 matches.forEach(p=>{const card=el('article',undefined,'chat-match-card'),img=el('img');img.src=p.image;img.alt=p.alt;img.loading='lazy';const body=el('div',undefined,'chat-match-body');body.append(el('span',`${p.country.toUpperCase()} · ${p.days===null?'DURATION ON REQUEST':p.days+' DAYS'}`,'package-meta'),el('h3',p.title),el('p',p.source==='mcp'?p.priceLabel:`From ${money(p.price)} / person`,'match-price'));const reasons=el('ul');p.reasons.forEach(reason=>reasons.append(el('li',reason)));body.append(reasons);const actions=el('div',undefined,'match-actions');const details=el('button','Details ↗','match-details');details.addEventListener('click',()=>openPackage(p));const tailor=el('button','View full itinerary →','button green');tailor.addEventListener('click',()=>openPackage(p));actions.append(details,tailor);body.append(actions);card.append(img,body);cards.append(card);});section.append(cards);messages.append(section);section.scrollIntoView({behavior:'instant',block:'nearest'});
}

function openConnectedPackage(p){
 const root=$('#dialog-content');root.replaceChildren(el('p','PACKAGE DETAILS','eyebrow'));const title=el('h2',p.title);title.id='dialog-title';root.append(title,el('p',p.priceLabel),el('p',p.route),el('p',p.description));
 for(const [heading,items] of [['Itinerary',p.stops],['Included',p.inclusions],['Not included',p.exclusions],['Important information',p.notes]]){if(!items.length)continue;root.append(el('h3',heading));const list=el('ul');items.forEach(item=>list.append(el('li',item)));root.append(list);}
 root.append(el('p','Concept image only. Final availability, terms and pricing require confirmation. No booking or payment is made here.','fine'));const discuss=el('button','Discuss this package →','button green');discuss.addEventListener('click',()=>{$('#package-dialog').close();send('Please explain '+p.title+' without changing its itinerary or price, and list the essential conditions.');});root.append(discuss);$('#package-dialog').showModal();$('#package-dialog').scrollTop=0;$('#dialog-title').setAttribute('tabindex','-1');$('#dialog-title').focus({preventScroll:true});
}
if(config.mode==='n8n'){
 $('.chat-top span').textContent=config.webhookUrl?'Safari concierge · Package discovery · v3':'Safari concierge · Setup pending';
 form.querySelector('button[type=submit]').textContent='Find matching packages ↗';
 form.querySelector('.fine').textContent='Search existing packages. No payment or reservation is made.';
 $('#faq details:nth-child(5) p').textContent='The concierge uses a connected planning service to search for packages. Prices and availability still need confirmation before booking.';
 $('.chat-note').textContent='Connected recommendations. Availability and final quotations require confirmation. The homepage collection and contact form remain demonstrations.';
 messages.replaceChildren(el('div','Welcome. Tell me where, when and how you would like to travel. I will look for suitable packages and show the returned options here.','message assistant'));
 welcome.replaceChildren(document.createTextNode('Welcome. Tell me your destination, travel dates, party size and per-person budget to explore suitable packages.'));
 const privacy=$('#faq details:last-child p');privacy.textContent='In connected concierge mode, your messages and travel preferences are sent to our planning service. The operator must provide its retention and deletion policy before public launch. Contact and sample itinerary tools remain demonstrations.';
}
